Bugfix: Prerender Error (#70)
* Update references to eggspress.org to eggspress.vercel.app (no longer control eggspress.org domain)

* Upgrade nextjs and other core packages

* Update dependencies

* Attempt to fix pre-render bug

Error: Objects are not valid as a React child (found: object with keys {metadata, error}). If you meant to render a collection of children, use an array instead.